### PR TITLE
support parameterized jobs; closes #236

### LINKED ISSUE #236: [server] add support for parameterized jenkins jobs

### PR DESCRIPTION
**Pull request by thuey**

### CODE REVIEW

**Comment by jonnymbgood** [comment]
It looks like you are matching the params by order? Would it be better to have them pass in key/value pairs and match the keys together (a la `trigger jenkins -p tag=1.0.0`)?

As an aside, I think we should update check kubernetes to pass the namespace in via `-n namespace` and move toward a parameterized format.

**Comment by thuey** [comment]
I know we talked about this, but as I thought about it, the more I realized how verbose that becomes and didn't like it. We should talk about it. I

**Comment by thuey** [comment]
Would it be alright with you if we go ahead and merge this in and then do any parameter rework in a separate issue that could include k8s?

**Comment by jonnymbgood** [comment]
that's fine.

**Pull request merged**
